import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const alice = localFont({
  src: "../../public/fonts/Alice-Regular.ttf",
  variable: "--font-alice",
  weight: "400",
  display: "swap",
});
const allison = localFont({
  src: "../../public/fonts/Allison-Regular.ttf",
  variable: "--font-allison",
  weight: "400",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${alice.variable} ${allison.variable}`}>
        {children}
      </body>
    </html>
  );
}
